import { writeFileSync } from "node:fs";
import { resolve, sep } from "node:path";
import {
  culturalCatalogVerifiedAt,
  culturalEvents,
} from "../src/data/cultural-events";
import {
  entertainmentExperiences,
  entertainmentVerifiedAt,
} from "../src/data/entertainment";
import {
  RESTAURANT_SCAN_DATE,
  restaurants,
} from "../src/data/restaurants";
import { resolveGothenburgPoint } from "../src/lib/geo";

type DiscoverySeed = {
  sourceKind: "culture" | "entertainment" | "restaurant";
  sourceId: string;
  title: string;
  category: string;
  address: string | null;
  area: string;
  sourceUrl: string;
  latitude: number;
  longitude: number;
  precision: "exact" | "area";
  verifiedAt: string;
};

const targetArgument = process.argv[2];
if (!targetArgument) {
  throw new Error("Usage: generate-discovery-seed.ts <migration.sql>");
}

const projectRoot = resolve(import.meta.dirname, "..");
const migrationsRoot = resolve(projectRoot, "supabase", "migrations");
const target = resolve(projectRoot, targetArgument);

if (
  !target.startsWith(`${migrationsRoot}${sep}`) ||
  !target.match(/_(?:seed_discovery_places|refresh_discovery_locations)\.sql$/)
) {
  throw new Error("Target must be a discovery seed or location refresh migration file.");
}

const seeds: DiscoverySeed[] = [];

for (const event of culturalEvents) {
  const point = resolveGothenburgPoint(event.venue, event.area, event.title);
  if (!point) continue;
  seeds.push({
    sourceKind: "culture",
    sourceId: event.id,
    title: event.title,
    category: event.category,
    address: event.venue,
    area: event.area,
    sourceUrl: event.sourceUrl,
    latitude: point.latitude,
    longitude: point.longitude,
    precision: point.precision,
    verifiedAt: culturalCatalogVerifiedAt,
  });
}

for (const experience of entertainmentExperiences) {
  const point = resolveGothenburgPoint(experience.title, experience.area);
  if (!point) continue;
  seeds.push({
    sourceKind: "entertainment",
    sourceId: experience.id,
    title: experience.title,
    category: experience.category,
    address: null,
    area: experience.area,
    sourceUrl: experience.url,
    latitude: point.latitude,
    longitude: point.longitude,
    precision: point.precision,
    verifiedAt: entertainmentVerifiedAt,
  });
}

for (const restaurant of restaurants) {
  const point = resolveGothenburgPoint(
    restaurant.address,
    restaurant.area,
    restaurant.name,
  );
  if (!point) continue;
  seeds.push({
    sourceKind: "restaurant",
    sourceId: restaurant.id,
    title: restaurant.name,
    category: restaurant.cuisine,
    address: restaurant.address,
    area: restaurant.area,
    sourceUrl: restaurant.sourceUrl,
    latitude: point.latitude,
    longitude: point.longitude,
    precision: point.precision,
    verifiedAt: restaurant.lastVerified ?? RESTAURANT_SCAN_DATE,
  });
}

function literal(value: string | null) {
  if (value === null) return "null";
  return `'${value.replaceAll("'", "''")}'`;
}

function row(seed: DiscoverySeed) {
  return `(${[
    literal(seed.sourceKind),
    literal(seed.sourceId),
    literal(seed.title),
    literal(seed.category),
    literal(seed.address),
    literal(seed.area),
    literal(seed.sourceUrl),
    `extensions.st_setsrid(extensions.st_makepoint(${seed.longitude}, ${seed.latitude}), 4326)::extensions.geography`,
    literal(seed.precision),
    `${literal(`${seed.verifiedAt}T12:00:00Z`)}::timestamptz`,
  ].join(", ")})`;
}

const statements: string[] = [
  "-- Generated by scripts/generate-discovery-seed.ts. Do not edit rows by hand.",
  `-- ${seeds.length} mapped catalogue records from the checked-in data sources.`,
  "",
];

for (let index = 0; index < seeds.length; index += 250) {
  const chunk = seeds.slice(index, index + 250);
  statements.push(
    "insert into public.discovery_places (",
    "  source_kind, source_id, title, category, address, area, source_url,",
    "  location, location_precision, verified_at",
    ") values",
    chunk.map(row).join(",\n"),
    "on conflict (source_kind, source_id) do update set",
    "  title = excluded.title,",
    "  category = excluded.category,",
    "  address = excluded.address,",
    "  area = excluded.area,",
    "  source_url = excluded.source_url,",
    "  location = excluded.location,",
    "  location_precision = excluded.location_precision,",
    "  verified_at = excluded.verified_at,",
    "  updated_at = now();",
    "",
  );
}

writeFileSync(target, `${statements.join("\n")}\n`, "utf8");
console.log(`Generated ${seeds.length} discovery places in ${target}`);
