-- STADEN editorial workspace
-- The UI gate is only a convenience. These RLS policies are the authority.

create or replace function public.is_staden_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin',
    false
  );
$$;

revoke all on function public.is_staden_admin() from public;
grant execute on function public.is_staden_admin() to authenticated;

create table public.editorial_posts (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (char_length(title) between 1 and 120),
  kicker text not null default 'STADEN väljer' check (char_length(kicker) <= 80),
  dek text not null default '' check (char_length(dek) <= 240),
  body_markdown text not null check (char_length(body_markdown) between 1 and 50000),
  hero_image_url text,
  hero_image_path text,
  image_alt text not null default '' check (char_length(image_alt) <= 240),
  image_caption text check (char_length(image_caption) <= 300),
  status text not null default 'draft'
    check (status in ('draft', 'review', 'scheduled', 'published')),
  publish_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint published_posts_need_a_date
    check (status <> 'published' or publish_at is not null)
);

create index editorial_posts_public_feed_idx
  on public.editorial_posts (publish_at desc)
  where status = 'published';

create index editorial_posts_status_updated_idx
  on public.editorial_posts (status, updated_at desc);

create table public.editorial_post_items (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.editorial_posts(id) on delete cascade,
  item_type text not null check (item_type in ('culture', 'restaurant')),
  item_id text not null check (char_length(item_id) between 1 and 180),
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now(),
  unique (post_id, item_type, item_id)
);

create index editorial_post_items_order_idx
  on public.editorial_post_items (post_id, position);

alter table public.editorial_posts enable row level security;
alter table public.editorial_post_items enable row level security;

create policy "published editorial posts are public"
on public.editorial_posts
for select
to anon, authenticated
using (status = 'published' and publish_at <= now());

create policy "admins manage editorial posts"
on public.editorial_posts
for all
to authenticated
using (public.is_staden_admin())
with check (public.is_staden_admin());

create policy "published editorial selections are public"
on public.editorial_post_items
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.editorial_posts post
    where post.id = editorial_post_items.post_id
      and post.status = 'published'
      and post.publish_at <= now()
  )
);

create policy "admins manage editorial selections"
on public.editorial_post_items
for all
to authenticated
using (public.is_staden_admin())
with check (public.is_staden_admin());

-- Explicit grants matter for projects where new tables are not automatically
-- exposed with broad Data API privileges. RLS still filters every row.
grant select on public.editorial_posts, public.editorial_post_items to anon;
grant select, insert, update, delete on public.editorial_posts, public.editorial_post_items to authenticated;
grant usage, select on sequence public.editorial_post_items_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'editorial-media',
  'editorial-media',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "admins list editorial media"
on storage.objects
for select
to authenticated
using (bucket_id = 'editorial-media' and public.is_staden_admin());

create policy "admins upload editorial media to their folder"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'editorial-media'
  and public.is_staden_admin()
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy "admins update their editorial media"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'editorial-media'
  and public.is_staden_admin()
  and (storage.foldername(name))[1] = (select auth.uid()::text)
)
with check (
  bucket_id = 'editorial-media'
  and public.is_staden_admin()
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy "admins delete their editorial media"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'editorial-media'
  and public.is_staden_admin()
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

comment on table public.editorial_posts is
  'Curated STADEN stories. Drafts are private; only due published rows are public.';
comment on table public.editorial_post_items is
  'Ordered references from editorial stories to the app-owned culture and restaurant catalogs.';
