create extension if not exists postgis with schema extensions;

create table if not exists public.discovery_places (
  id bigint generated by default as identity primary key,
  source_kind text not null,
  source_id text not null,
  title text not null,
  category text,
  address text,
  area text,
  source_url text,
  location extensions.geography(Point, 4326) not null,
  location_precision text not null default 'exact',
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint discovery_places_source_kind_check
    check (source_kind in ('culture', 'entertainment', 'restaurant')),
  constraint discovery_places_location_precision_check
    check (location_precision in ('exact', 'area')),
  constraint discovery_places_source_identity_key
    unique (source_kind, source_id)
);

create index if not exists discovery_places_location_gix
  on public.discovery_places
  using gist (location);

create index if not exists discovery_places_source_kind_idx
  on public.discovery_places (source_kind);

alter table public.discovery_places enable row level security;

drop policy if exists "Public catalogue places are readable"
  on public.discovery_places;

create policy "Public catalogue places are readable"
  on public.discovery_places
  for select
  to anon, authenticated
  using (true);

revoke all on table public.discovery_places from public;
revoke all on table public.discovery_places from anon, authenticated;
grant select on table public.discovery_places to anon, authenticated;

create or replace function public.nearby_discovery_places(
  user_lat double precision,
  user_lng double precision,
  radius_m integer default 3000,
  place_kinds text[] default array['culture', 'entertainment', 'restaurant']::text[],
  result_limit integer default 100
)
returns table (
  id bigint,
  source_kind text,
  source_id text,
  title text,
  category text,
  address text,
  area text,
  source_url text,
  location_precision text,
  verified_at timestamptz,
  distance_m integer
)
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
  origin extensions.geography;
begin
  if user_lat is null or user_lat < -90 or user_lat > 90 then
    raise exception 'user_lat must be between -90 and 90'
      using errcode = '22023';
  end if;

  if user_lng is null or user_lng < -180 or user_lng > 180 then
    raise exception 'user_lng must be between -180 and 180'
      using errcode = '22023';
  end if;

  if radius_m is null or radius_m < 100 or radius_m > 50000 then
    raise exception 'radius_m must be between 100 and 50000'
      using errcode = '22023';
  end if;

  if place_kinds is null
    or cardinality(place_kinds) = 0
    or not place_kinds <@ array['culture', 'entertainment', 'restaurant']::text[]
  then
    raise exception 'place_kinds contains an unsupported value'
      using errcode = '22023';
  end if;

  origin := extensions.st_setsrid(
    extensions.st_makepoint(user_lng, user_lat),
    4326
  )::extensions.geography;

  return query
  select
    place.id,
    place.source_kind,
    place.source_id,
    place.title,
    place.category,
    place.address,
    place.area,
    place.source_url,
    place.location_precision,
    place.verified_at,
    round(extensions.st_distance(place.location, origin))::integer as distance_m
  from public.discovery_places as place
  where place.source_kind = any (place_kinds)
    and extensions.st_dwithin(place.location, origin, radius_m)
  order by place.location operator(extensions.<->) origin
  limit least(greatest(coalesce(result_limit, 100), 1), 200);
end;
$$;

revoke all on function public.nearby_discovery_places(
  double precision,
  double precision,
  integer,
  text[],
  integer
) from public;

grant execute on function public.nearby_discovery_places(
  double precision,
  double precision,
  integer,
  text[],
  integer
) to anon, authenticated;

comment on table public.discovery_places is
  'Public catalogue records with a PostGIS point for distance-based discovery.';

comment on function public.nearby_discovery_places is
  'Returns public catalogue places within a validated radius, nearest first.';
